#!/bin/sh

# dnsproxy This shell script takes care of starting and stopping
#
# chkconfig: - 60 50
# description: the dns proxy server daemon
# processname: dnsproxy

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
prog="DNSPROXY"

# jdk的安装目录
JAVA_HOME=/usr/java/jdk1.7.0_71
#应用程序的目录
DNSPROXY_HOME=/root/dnsProxy
#jsvc所在的目录
DAEMON_HOME=$DNSPROXY_HOME
#用户
DNSPROXY_USER=root
#主类
DNSPROXY_MAIN=org.foxteam.noisyfox.dnsproxy.Bootstrap

# for multi instances adapt those lines.
TMP_DIR=/var/tmp
PID_FILE=/var/run/dns_proxy.pid

#程序运行是所需的jar包，commons-daemon.jar是不能少的
CLASSPATH=\
$DNSPROXY_HOME/dnsProxy.jar:\
$DNSPROXY_HOME/commons-daemon.jar:\

case "$1" in
start)
#
# Start Serivce
#
$DAEMON_HOME/jsvc \
-user $DNSPROXY_USER \
-home $JAVA_HOME \
-Djava.io.tmpdir=$TMP_DIR \
-wait 10 \
-pidfile $PID_FILE \
-outfile $DNSPROXY_HOME/log/dnsProxy.out \
-errfile '&1' \
-cp $CLASSPATH \
$DNSPROXY_MAIN \
server
#
# To get a verbose JVM
#-verbose \
# To get a debug of jsvc.
#-debug \
exit $?
;;

stop)
#
# Stop Serivce
#
$DAEMON_HOME/jsvc \
-stop \
-pidfile $PID_FILE \
$DNSPROXY_MAIN
exit $?
;;

*)
echo "Usage dnsproxy start/stop"
exit 1;;
esac

